!!net.sourceforge.marathon.objectmap.ObjectMapConfiguration
containerNamingProperties:
-   className: java.awt.Window
    propertyLists:
    -   priority: 100
        properties: [title]
-   className: javax.swing.JInternalFrame
    propertyLists:
    -   priority: 100
        properties: [title, internalFrameIndex]
containerRecognitionProperties:
-   className: java.awt.Window
    propertyLists:
    -   priority: 100
        properties: [oMapClassName]
    -   priority: 90
        properties: [component.class.name, title]
-   className: javax.swing.JInternalFrame
    propertyLists:
    -   priority: 100
        properties: [oMapClassName]
    -   priority: 90
        properties: [component.class.name, title]
generalProperties: [labeledBy, toolTipText, name, labelText, precedingLabel, cText,
    iconFile, position, size, accelerator, enabled, toolTipText, fieldName, layoutData.gridx,
    layoutData.gridy, layoutData.x, layoutData.y, accessibleContext.accessibleName]
namingProperties:
-   className: java.awt.Component
    propertyLists:
    -   priority: 100
        properties: [buttonText]
    -   priority: 90
        properties: [labeledBy]
    -   priority: 80
        properties: [accessibleName]
    -   priority: 70
        properties: [buttonIconFile]
    -   priority: 60
        properties: [precedingLabel]
    -   priority: 50
        properties: [toolTipText]
    -   priority: 40
        properties: [name]
    -   priority: 30
        properties: [fieldName]
    -   priority: 20
        properties: [actionCommand]
-   className: javax.swing.JLabel
    propertyLists:
    -   priority: 100
        properties: [labelText]
recognitionProperties:
-   className: java.awt.Component
    propertyLists:
    -   priority: 100
        properties: [name, type]
    -   priority: 90
        properties: [fieldName, type]
    -   priority: 80
        properties: [actionCommand, type]
    -   priority: 70
        properties: [buttonText, type]
    -   priority: 60
        properties: [labeledBy, type]
    -   priority: 50
        properties: [accessibleName, type]
    -   priority: 40
        properties: [buttonIconFile, type]
    -   priority: 30
        properties: [precedingLabel, type]
    -   priority: 20
        properties: [toolTipText, type]
