!!net.sourceforge.marathon.objectmap.ObjectMapConfiguration
containerNamingProperties:
-   className: java.awt.Window
    propertyLists:
    -   priority: 100
        properties: [title]
-   className: javax.swing.JInternalFrame
    propertyLists:
    -   priority: 100
        properties: [title, internalFrameIndex]
containerRecognitionProperties:
-   className: java.awt.Window
    propertyLists:
    -   priority: 100
        properties: [oMapClassName]
    -   priority: 90
        properties: [component.class.name, title]
-   className: javax.swing.JInternalFrame
    propertyLists:
    -   priority: 100
        properties: [oMapClassName]
    -   priority: 90
        properties: [component.class.name, title]
generalProperties: [position, size, accelerator, enabled, toolTipText, fieldName,
    layoutData.gridx, layoutData.gridy, layoutData.x, layoutData.y]
namingProperties:
-   className: java.awt.Component
    propertyLists:
    -   priority: 100
        properties: [name]
    -   priority: 70
        properties: [precedingLabel]
-   className: javax.swing.JLabel
    propertyLists:
    -   priority: 90
        properties: [labelText]
-   className: javax.swing.AbstractButton
    propertyLists:
    -   priority: 90
        properties: [cText]
    -   priority: 80
        properties: [iconFile]
-   className: javax.swing.JComponent
    propertyLists:
    -   priority: 90
        properties: [labeledBy]
    -   priority: 80
        properties: [toolTipText]
recognitionProperties:
-   className: java.awt.Component
    propertyLists:
    -   priority: 100
        properties: [name, type]
    -   priority: 70
        properties: [precedingLabel, type]
-   className: javax.swing.JLabel
    propertyLists:
    -   priority: 90
        properties: [labelText, type]
-   className: javax.swing.AbstractButton
    propertyLists:
    -   priority: 90
        properties: [cText, type]
    -   priority: 80
        properties: [iconFile, type]
-   className: javax.swing.JComponent
    propertyLists:
    -   priority: 90
        properties: [labeledBy, type]
    -   priority: 80
        properties: [toolTipText, type]
